# Generated by Django 6.0.3 on 2026-03-04 04:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=64)),
                (
                    "unit",
                    models.IntegerField(
                        choices=[
                            (0, "Piece"),
                            (1, "Kg"),
                            (2, "Meter"),
                            (3, "Liter"),
                            (4, "Box"),
                            (5, "Sq. meter"),
                            (6, "Cubic meter"),
                            (7, "Roll"),
                            (8, "Set"),
                            (9, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Unit rate/price",
                        max_digits=14,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "materials",
                "db_table": "inventory_material",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["account", "code"],
                        name="inventory_m_account_4a4e81_idx",
                    ),
                    models.Index(
                        fields=["account", "is_deleted"],
                        name="inventory_m_account_9e399f_idx",
                    ),
                ],
                "unique_together": {("account", "code")},
            },
        ),
    ]
