# Generated by Django 6.0.3 on 2026-03-04 04:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=64)),
                (
                    "project_type",
                    models.IntegerField(
                        choices=[
                            (0, "Residential"),
                            (1, "Commercial"),
                            (2, "Infrastructure"),
                            (3, "Renovation"),
                            (4, "Industrial"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Planning"),
                            (1, "Active"),
                            (2, "On Hold"),
                            (3, "Completed"),
                            (4, "Cancelled"),
                        ],
                        db_index=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=512)),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.account",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "projects",
                "db_table": "projects_project",
                "ordering": ["-start_date", "code"],
                "indexes": [
                    models.Index(
                        fields=["account", "code"],
                        name="projects_pr_account_88177a_idx",
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="projects_pr_account_57568c_idx",
                    ),
                    models.Index(
                        fields=["account", "is_deleted"],
                        name="projects_pr_account_4c9bfb_idx",
                    ),
                    models.Index(
                        fields=["client", "status"],
                        name="projects_pr_client__60b095_idx",
                    ),
                ],
                "unique_together": {("account", "code")},
            },
        ),
    ]
