# Generated by Django 6.0.3 on 2026-03-04 03:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Asset"),
                            (2, "Liability"),
                            (3, "Equity"),
                            (4, "Revenue"),
                            (5, "Expense"),
                        ],
                        db_index=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "accounting_chartofaccount",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_number", models.CharField(db_index=True, max_length=64)),
                ("entry_date", models.DateField(db_index=True)),
                ("posting_date", models.DateField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Manual"),
                            (1, "Sales"),
                            (2, "Purchase"),
                            (3, "Invoice"),
                            (4, "Payment"),
                            (5, "Adjustment"),
                            (6, "Opening balance"),
                            (7, "Other"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Posted"), (2, "Void")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_ledgerentry",
                "ordering": ["-posting_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveSmallIntegerField(default=1)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
            ],
            options={
                "db_table": "accounting_ledgerline",
                "ordering": ["entry", "line_number"],
            },
        ),
    ]
