# Generated by Django 6.0.3 on 2026-03-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccount",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chart_of_accounts",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="accounting.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="accounts.account",
            ),
        ),
    ]
