# Generated by Django 6.0.3 on 2026-03-04 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_ledger_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_ledger_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ledgerline",
            name="chart_of_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_lines",
                to="accounting.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="ledgerline",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.ledgerentry",
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(
                fields=["account", "is_active"], name="accounting__account_289242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(
                fields=["parent"], name="accounting__parent__3124f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chartofaccount",
            constraint=models.UniqueConstraint(
                fields=("account", "code"), name="accounting_coa_account_code_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["account", "entry_date"], name="accounting__account_91ef43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["account", "status"], name="accounting__account_321415_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("account", "entry_number"),
                name="accounting_entry_account_number_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerline",
            index=models.Index(
                fields=["chart_of_account", "created_at"],
                name="accounting__chart_o_0b8f9c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerline",
            constraint=models.UniqueConstraint(
                fields=("entry", "line_number"), name="accounting_line_entry_line_uniq"
            ),
        ),
    ]
