# Generated by Django 6.0.3 on 2026-03-05 17:06

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=apps.core.models.document_upload_to),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "core_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField(db_index=True)),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("object_repr", models.CharField(max_length=200)),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Change"), (3, "Deletion")],
                        db_index=True,
                    ),
                ),
                ("change_message", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="accounts.account",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "core_activitylog",
                "ordering": ["-action_time"],
            },
        ),
    ]
