# Generated by Django 6.0.3

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("companies", "0001_initial"),
        ("projects", "0001_add_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Posted")], db_index=True, default=0
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "General"),
                            (1, "Project"),
                            (2, "Outsourced labor"),
                            (3, "Employee-paid"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "labor_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Hourly"), (1, "Daily")],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("employee_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("employee_name", models.CharField(blank=True, max_length=255)),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[(0, "Cash"), (1, "Bank")], db_index=True, default=0
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not completed"),
                            (1, "Completed"),
                            (2, "Partial"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="accounts.account",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-date", "-created_at"],
                "verbose_name_plural": "expenses",
            },
        ),
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="expenses.expense",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expensepayment",
                "ordering": ["-date", "id"],
                "verbose_name_plural": "expense payments",
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["account", "status"], name="expenses_exp_account_ix1"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["account", "date"], name="expenses_exp_account_ix2"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["account", "category"], name="expenses_exp_account_ix3"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["account", "is_deleted"], name="expenses_exp_account_ix4"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["payee"], name="expenses_exp_payee_ix"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["project"], name="expenses_exp_project_ix"),
        ),
        migrations.AddIndex(
            model_name="expensepayment",
            index=models.Index(fields=["expense"], name="expenses_expay_expense_ix1"),
        ),
        migrations.AddIndex(
            model_name="expensepayment",
            index=models.Index(fields=["expense", "is_deleted"], name="expenses_expay_expense_ix2"),
        ),
    ]
