# Generated by Django 6.0.3 on 2026-03-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_account_d1696f_idx",
            old_name="expenses_exp_account_ix1",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_account_aad602_idx",
            old_name="expenses_exp_account_ix2",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_account_7ed937_idx",
            old_name="expenses_exp_account_ix3",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_account_260d57_idx",
            old_name="expenses_exp_account_ix4",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_payee_i_46b253_idx",
            old_name="expenses_exp_payee_ix",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expenses_ex_project_4e1d75_idx",
            old_name="expenses_exp_project_ix",
        ),
        migrations.RenameIndex(
            model_name="expensepayment",
            new_name="expenses_ex_expense_8804ae_idx",
            old_name="expenses_expay_expense_ix1",
        ),
        migrations.RenameIndex(
            model_name="expensepayment",
            new_name="expenses_ex_expense_94efa4_idx",
            old_name="expenses_expay_expense_ix2",
        ),
    ]
