# Generated by Django 6.0.3 on 2026-03-04 05:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("companies", "0001_initial"),
        ("inventory", "0001_add_material"),
        ("projects", "0001_add_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(db_index=True, max_length=128)),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Posted")], db_index=True, default=0
                    ),
                ),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[(0, "Cash"), (1, "Bank")], db_index=True, default=0
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total of line items",
                        max_digits=14,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not completed"),
                            (1, "Completed"),
                            (2, "Partial"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="accounts.account",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="projects.project",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchases",
                "db_table": "purchase_purchase",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="quantity * rate",
                        max_digits=14,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_line_items",
                        to="inventory.material",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="purchase.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase line items",
                "db_table": "purchase_lineitem",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchase.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase payments",
                "db_table": "purchase_payment",
                "ordering": ["-date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["account", "status"], name="purchase_pu_account_56f2f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["account", "date"], name="purchase_pu_account_7f298c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["account", "is_deleted"], name="purchase_pu_account_8a352e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier"], name="purchase_pu_supplie_b1e56b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["project"], name="purchase_pu_project_bdc5df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaselineitem",
            index=models.Index(
                fields=["purchase"], name="purchase_li_purchas_aa0ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaselineitem",
            index=models.Index(
                fields=["purchase", "is_deleted"], name="purchase_li_purchas_63e7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasepayment",
            index=models.Index(
                fields=["purchase"], name="purchase_pa_purchas_ae989c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasepayment",
            index=models.Index(
                fields=["purchase", "is_deleted"], name="purchase_pa_purchas_7445ee_idx"
            ),
        ),
    ]
