# Generated by Django 6.0.3 on 2026-03-04 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("support_email", models.EmailField(blank=True, max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Active"), (1, "Inactive")],
                        db_index=True,
                        default=0,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_account",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="accounts_ac_name_5f6f46_idx"),
                    models.Index(
                        fields=["status", "is_deleted"],
                        name="accounts_ac_status_80d336_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="accounts_ac_created_25027f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "Admin"), (1, "Accountant"), (2, "System")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "availability",
                    models.IntegerField(
                        choices=[(0, "Offline"), (1, "Online")],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_users",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_accountuser",
                "ordering": ["-created_at"],
            },
        ),
    ]
