# Generated by Django 6.0.3 on 2026-03-04 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(
                fields=["account", "user"], name="accounts_ac_account_164555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(fields=["role"], name="accounts_ac_role_fb54b4_idx"),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(
                fields=["availability"], name="accounts_ac_availab_1a6c77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountuser",
            unique_together={("account", "user")},
        ),
    ]
