# Generated by Django 6.0.3 on 2026-03-04 19:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                ("nationality", models.CharField(blank=True, max_length=128)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "qid_number",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("qid_expiry_date", models.DateField(blank=True, null=True)),
                ("passport_number", models.CharField(blank=True, max_length=64)),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                ("visa_number", models.CharField(blank=True, max_length=64)),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "sponsorship_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Company"), (1, "Family"), (2, "Transfer")],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Internal employee ID",
                        max_length=64,
                    ),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Permanent"), (1, "Contract"), (2, "Temporary")],
                        db_index=True,
                        null=True,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=128)),
                ("department", models.CharField(blank=True, max_length=128)),
                (
                    "employment_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Active"), (1, "On Leave"), (2, "Terminated")],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "transportation_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "other_allowances",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("health_card_number", models.CharField(blank=True, max_length=64)),
                (
                    "health_insurance_policy",
                    models.CharField(blank=True, max_length=128),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "employees",
                "db_table": "employees_employee",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Advance, Remaining amount, Bonus, Adjustment",
                        max_length=255,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_entries",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "employee salary entries",
                "db_table": "employees_employeesalaryentry",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. salary_payment, advance, reimbursement, deduction",
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "employee transactions",
                "db_table": "employees_employeetransaction",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["account", "is_deleted"], name="employees_e_account_ad415d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["account", "employment_status"],
                name="employees_e_account_4324ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["account", "department"], name="employees_e_account_7060fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeesalaryentry",
            index=models.Index(
                fields=["employee", "is_deleted"], name="employees_e_employe_8efa1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetransaction",
            index=models.Index(
                fields=["employee", "is_deleted"], name="employees_e_employe_e89009_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetransaction",
            index=models.Index(
                fields=["employee", "date"], name="employees_e_employe_dd8d41_idx"
            ),
        ),
    ]
