# Generated by Django 6.0.3 on 2026-03-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "company_type",
                    models.IntegerField(
                        choices=[(0, "Client"), (1, "Supplier"), (2, "Subcontractor")],
                        db_index=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "companies_company",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["account", "company_type"],
                        name="companies_c_account_2fe3d3_idx",
                    ),
                    models.Index(
                        fields=["account", "is_deleted"],
                        name="companies_c_account_9bdc92_idx",
                    ),
                ],
            },
        ),
    ]
