# Generated by Django 6.0.3 on 2026-03-05 17:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_type",
                    models.IntegerField(
                        choices=[(0, "Client"), (1, "Subcontractor")],
                        db_index=True,
                        help_text="0=Client (receivable), 1=Subcontractor (payable).",
                    ),
                ),
                ("reference", models.CharField(db_index=True, max_length=128)),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Posted")], db_index=True, default=0
                    ),
                ),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[(0, "Cash"), (1, "Bank")], db_index=True, default=0
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Invoice amount.",
                        max_digits=14,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not completed"),
                            (1, "Completed"),
                            (2, "Partial"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.account",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Client or subcontractor company.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="companies.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "invoices",
                "db_table": "invoices_invoice",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Posted")], db_index=True, default=0
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "invoice payments",
                "db_table": "invoices_invoicepayment",
                "ordering": ["-date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["account", "status"], name="invoices_in_account_62d892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["account", "invoice_type"],
                name="invoices_in_account_ad0b6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["account", "date"], name="invoices_in_account_c315c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["account", "is_deleted"], name="invoices_in_account_e9816e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["party"], name="invoices_in_party_i_4b1196_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["project"], name="invoices_in_project_3171df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(
                fields=["invoice"], name="invoices_in_invoice_3d205d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(
                fields=["invoice", "is_deleted"], name="invoices_in_invoice_555207_idx"
            ),
        ),
    ]
