# Generated by Django 6.0.3 on 2026-03-05 12:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoicelineitem",
            name="invoices_in_invoice_91407a_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicelineitem",
            name="invoices_in_invoice_585eb1_idx",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Invoice amount.",
                max_digits=14,
            ),
        ),
        migrations.DeleteModel(
            name="InvoiceLineItem",
        ),
    ]
