"""Constants for projects app."""

# Project type values (IntegerField)
PROJECT_TYPE_RESIDENTIAL = 0
PROJECT_TYPE_COMMERCIAL = 1
PROJECT_TYPE_INFRASTRUCTURE = 2
PROJECT_TYPE_RENOVATION = 3
PROJECT_TYPE_INDUSTRIAL = 4

PROJECT_TYPE_CHOICES = [
    (PROJECT_TYPE_RESIDENTIAL, "Residential"),
    (PROJECT_TYPE_COMMERCIAL, "Commercial"),
    (PROJECT_TYPE_INFRASTRUCTURE, "Infrastructure"),
    (PROJECT_TYPE_RENOVATION, "Renovation"),
    (PROJECT_TYPE_INDUSTRIAL, "Industrial"),
]

# Project status values (IntegerField)
PROJECT_STATUS_PLANNING = 0
PROJECT_STATUS_ACTIVE = 1
PROJECT_STATUS_ONHOLD = 2
PROJECT_STATUS_COMPLETED = 3
PROJECT_STATUS_CANCELLED = 4

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_PLANNING, "Planning"),
    (PROJECT_STATUS_ACTIVE, "Active"),
    (PROJECT_STATUS_ONHOLD, "On Hold"),
    (PROJECT_STATUS_COMPLETED, "Completed"),
    (PROJECT_STATUS_CANCELLED, "Cancelled"),
]
